### ISSUE TITLE
Unhandled error has occured

### ISSUE THREAD

**Issue by mek363** [microsoft/EventLogExpert#252] opened 2023-11-13 16:40 UTC
I repeatedly run into this error appearing at the bottom of the screen and then prompting me to reload. I am running 23.10.17.922 on Windows 10. I am attempting load a folder full of 355 evtx files from another machine. I get the error after load when I try to navigate (PgDn). Are the debug logs stored somewhere?

**Comment by mek363** [comment] 2023-11-13 16:46
The app also crashed and I see this in my Application log.

Log Name: Application
Source: Application Error
Date: 11/13/2023 10:42:50 AM
Event ID: 1000
Task Category: (100)
Level: Error
Keywords: Classic
User:
Computer: KRAMEM7-L5.ent.core.medtronic.com
Description:
Faulting application name: EventLogExpert.exe, version: 23.10.17.922, time stamp: 0x6514d416
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3570, time stamp: 0xda674bb7
Exception code: 0xc000027b
Fault offset: 0x000000000012dd42
Faulting process id: 0x4a0c
Faulting application start time: 0x01da16460f659359
Faulting application path: C:\Program Files\WindowsApps\eventlogexpert_23.10.17.922_x64__8wekyb3d8bbwe\EventLogExpert.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 915f66e5-9980-4ea8-9137-b6a36934bf0b
Faulting package full name: eventlogexpert_23.10.17.922_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>Error</Level>
    <Task>(100)</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-11-13T16:42:50.2677383Z" />
    <EventRecordID>118878</EventRecordID>
    <Channel>Application</Channel>
    <Computer>KRAMEM7-L5.ent.core.medtronic.com</Computer>
    <ProcessID>0</ProcessID>
    <ThreadID>0</ThreadID>
  </System>
  <EventData>
    <Data>EventLogExpert.exe</Data>
    <Data>23.10.17.922</Data>
    <Data>6514d416</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.3570</Data>
    <Data>da674bb7</Data>
    <Data>c000027b</Data>
    <Data>000000000012dd42</Data>
    <Data>4a0c</Data>
    <Data>01da16460f659359</Data>
    <Data>C:\Program Files\WindowsApps\eventlogexpert_23.10.17.922_x64__8wekyb3d8bbwe\EventLogExpert.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>915f66e5-9980-4ea8-9137-b6a36934bf0b</Data>
    <Data>eventlogexpert_23.10.17.922_x64__8wekyb3d8bbwe</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by jschick04** [comment] 2023-11-13 16:54
Log file is located "%AppData%\Local\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState".

Do you see the error with a single log as well or only when multiple logs are loaded?

Why specifically are you trying to load a folder with 355 evtx files?

**Comment by mek363** [comment] 2023-11-13 20:49
Why = that was the dump I got from the other computer and I didn't know specifically which file I might find a clue in. Here is the debug.log. I think I recall getting the error with a single file too, but I would have to try again.
[debug.log](https://github.com/microsoft/EventLogExpert/files/13341214/debug.log)

**Comment by jschick04** [comment] 2023-11-14 15:04
See if you can reproduce the issue with a single file but what looks like is happening is that there may be duplicate logs being imported which causes an exception due to a duplicate key.

We protect against this if you try to import the same file twice but not if the log file has a different name.

I can reproduce this issue by taking an evtx file, copying and pasting to the same directory to create a duplicate of the file with a different name and attempt to import both files.

**Comment by bill-long** [comment] 2023-11-27 08:37
This is fixed in the latest prerelease.

**Closed by bill-long** 2023-11-27 08:37 UTC
Labels: bug
